language: scala
scala:
  - 2.13.1
jdk:
  - openjdk8
env:
  global:
    - TIMEOUT_SEC=720
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
install:
  - git clone https://github.com/izgzhen/android-platforms
script:
  - make init
  - make
  - make test
