language: scala
scala:
  - 2.13.1
jdk:
  - openjdk8
env:
  global:
    - TIMEOUT_SEC=720
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
install:
  - wget --quiet https://github.com/izgzhen/android-platforms/releases/download/v0.1/android-tools-linux.zip
  - unzip -q android-tools-linux.zip -d android-tools-linux
  - yes | android-tools-linux/tools/bin/sdkmanager --licenses
  - android-tools-linux/tools/bin/sdkmanager 'platforms;android-19'
script:
  - make init
  - make
  - ANDROID_SDK=$PWD/android-tools-linux make test
