#!/bin/bash
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
jspath=$(realpath $1)
JAR=target/seguard-1.0-SNAPSHOT-jar-with-dependencies.jar
cd $SCRIPTDIR
make
java -jar $JAR --lang js --js $jspath --mode core --sourceSinkFile SourcesAndSinksJS.txt --dotPath $jspath.dot
