#!/bin/bash
set -e
set -x

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
jspath=$(realpath $1)
JAR=target/seguard-1.0-SNAPSHOT-jar-with-dependencies.jar
cd $SCRIPTDIR
make
tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
java -jar $JAR --lang js --js $jspath --mode entrypoints --sourceSinkFile SourcesAndSinksJS.txt --outputPath $tmpfile
#java -jar $JAR --lang js --js $jspath --mode core --sourceSinkFile SourcesAndSinksJS.txt --dotPath $jspath.seguardjs.dot
