#!/bin/bash
set -e
set -x

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
jspath=$(realpath $1)
JAR=target/seguard-1.0-SNAPSHOT-jar-with-dependencies.jar
cd $SCRIPTDIR
make
tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
tmpfile2=$(mktemp /tmp/abc-script.XXXXXX)
java -jar $JAR --lang js --js $jspath --mode entrypoints --sourceSinkFile SourcesAndSinksJS.txt --outputPath $tmpfile
cat $tmpfile $jspath > $tmpfile2
java -jar $JAR --lang js --js $tmpfile2 --mode core --sourceSinkFile SourcesAndSinksJS.txt --outputPath $jspath.seguardjs.dot
